TaskTracker.Web/Models/ErrorViewModel.cs
using System;

namespace TaskTracker.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TaskTracker.Web/Controllers/ProjectsController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TaskTracker.Application.Common.ViewModels;
using TaskTracker.Application.Core.Projects.Commands;
using TaskTracker.Application.Core.Projects.Queries;

namespace TaskTracker.Web.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly IMediator _mediator;
        public ProjectsController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _mediator.Send(new GetProjectsQuery()));
        }

        [HttpGet]
        public Task<IActionResult> Create()
        {          
            return Task.FromResult<IActionResult>(View(new CreateProjectCommand()));
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProjectCommand command)
        {
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ProjectViewModel project = await _mediator.Send(new GetProjectQuery { Id = id });
            return View(new UpdateProjectCommand { Id = id, ViewModel = project });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, UpdateProjectCommand command)
        {
            if (id != command.Id)
            {
                return BadRequest();            
            }
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _mediator.Send(new DeleteProjectCommand { Id = id });
            return RedirectToAction(nameof(Index));
        }
    }
}

TaskTracker.Web/Controllers/TaskController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TaskTracker.Application.Common.ViewModels;
using TaskTracker.Application.Core.Projects.Commands;
using TaskTracker.Application.Core.Projects.Queries;
using TaskTracker.Application.Core.Tasks.Commands;

namespace TaskTracker.Web.Controllers
{
    public class TaskController : Controller
    {
        private readonly IMediator _mediator;
        public TaskController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _mediator.Send(new GetTasksQuery()));
        }

        [HttpGet]
        public PartialViewResult Create()
        {
            return PartialView("Create", new CreateTaskCommand());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateTaskCommand command)
        {
            await _mediator.Send(command);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            TaskViewModel task = await _mediator.Send(new GetTaskQuery { Id = id });

            return PartialView(new UpdateTaskCommand { Id = id, ViewModel = task });
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateTaskCommand command)
        {
            if (id != command.Id)
            {
                return BadRequest();
            }

            await _mediator.Send(command);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _mediator.Send(new DeleteTaskCommand { Id = id });

            return RedirectToAction(nameof(Index));
        }
    }
}

TaskTracker.Web/Controllers/TasksController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;
using TaskTracker.Application.Common.ViewModels;
using TaskTracker.Application.Core.Projects.Commands;
using TaskTracker.Application.Core.Projects.Queries;
using TaskTracker.Application.Core.Tasks.Commands;

namespace TaskTracker.Web.Controllers
{
    public class TasksController : Controller
    {
        private readonly IMediator _mediator;
        public TasksController(IMediator mediator)
        {
            _mediator = mediator;            
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            await LoadCollections();
            return View(await _mediator.Send(new GetTasksQuery()));           
        }

        [HttpGet]
        public async Task<PartialViewResult> Create()
        {
            await LoadCollections();
            return PartialView("Create", new CreateTaskCommand());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateTaskCommand command)
        {
            await _mediator.Send(command);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            await LoadCollections();
            TaskViewModel task = await _mediator.Send(new GetTaskQuery { Id = id });
            return PartialView(new UpdateTaskCommand { Id = id, ViewModel = task });
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateTaskCommand command)
        {
            if (id != command.Id)
            {
                return BadRequest();
            }
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _mediator.Send(new DeleteTaskCommand { Id = id });
            return RedirectToAction(nameof(Index));
        }

        private async Task LoadCollections()
        {
            List<ProjectViewModel>? projects = await _mediator.Send(new GetProjectsQuery());
            ViewBag.Projects = projects.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
        }
    }
}

TaskTracker.Web/Views/Projects/Create.cshtml
@model TaskTracker.Application.Core.Projects.Commands.CreateProjectCommand
@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Projects", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Name, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Status, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Priority, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Priority, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.StartDate, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.CompletionDate, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.CompletionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.CompletionDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Save" />
            <a class="btn btn-danger" asp-action="Index">Back</a>
        </div>
    </div>
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TaskTracker.Web/Views/Projects/Edit.cshtml
@model TaskTracker.Application.Core.Projects.Commands.UpdateProjectCommand
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "Projects", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Name, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Status, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Priority, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Priority, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.StartDate, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.CompletionDate, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.CompletionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.CompletionDate, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
                @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.Language, (IList<SelectListItem>)ViewBag.Languages, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Save" />
            <a class="btn btn-danger" asp-action="Index">Back</a>
        </div>
    </div>
}
@section Scripts 
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
     }
}

TaskTracker.Web/Views/Projects/Index.cshtml
@model List<TaskTracker.Application.Common.ViewModels.ProjectViewModel>


@{
    ViewBag.Title = "Projects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p style="text-align:right;margin-right:20px;">
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>

<table class="table table-bordered table-condensed">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Name)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Status)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Priority)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().StartDate)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().CompletionDate)</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var project in Model)
        {
            @Html.HiddenFor(_ => project.Id)
            <tr>
                <td>@Html.DisplayFor(_ => project.Name)</td>
                <td>@Html.DisplayFor(_ => project.Status)</td>
                <td>@Html.DisplayFor(_ => project.Priority)</td>
                <td>@Html.DisplayFor(_ => project.StartDate)</td>
                <td>@Html.DisplayFor(_ => project.CompletionDate)</td>
                <td class="text-center ">
                    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@project.Id">Edit</a>
                </td>
                <td class="text-center ">
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@project.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

TaskTracker.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskTracker.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />   
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Projects" asp-action="Index">TaskTracker.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="Index">Tasks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TaskTracker.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    
    @await Component.InvokeAsync("Toastify")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskTracker.Web/Views/Tasks/Create.cshtml
@model TaskTracker.Application.Core.Tasks.Commands.CreateTaskCommand
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Tasks", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Name, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Status, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Priority, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Priority, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Description, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.ProjectId, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.ViewModel.ProjectId, ViewBag.Projects as IEnumerable<SelectListItem>, "Select Project", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ViewModel.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Save" />
            <a class="btn btn-danger" asp-action="Index">Back</a>
        </div>
    </div>
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TaskTracker.Web/Views/Tasks/Edit.cshtml
@model TaskTracker.Application.Core.Tasks.Commands.UpdateTaskCommand
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Update", "Tasks", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Name, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Status, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Priority, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Priority, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.Description, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.ViewModel.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewModel.Description, "", new { @class = "text-danger" })
            </div>
        </div>
       <div class="form-group">
            @Html.LabelFor(model => model.ViewModel.ProjectId, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.ViewModel.ProjectId, ViewBag.Projects as IEnumerable<SelectListItem>, "Select Project", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ViewModel.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Save" />
            <a class="btn btn-danger" asp-action="Index">Back</a>
        </div>
    </div>
}
@section Scripts
    {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TaskTracker.Web/Views/Tasks/Index.cshtml
@model List<TaskTracker.Application.Common.ViewModels.TaskViewModel>


@{
    ViewBag.Title = "Tasks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p style="text-align:right;margin-right:20px;">
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>

<table class="table table-bordered table-condensed">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Name)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Status)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Priority)</th>
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Description)</th>
            <th>Project</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var task in Model)
        {
            @Html.HiddenFor(_ => task.Id)
        <tr>
            <td>@Html.DisplayFor(_ => task.Name)</td>
            <td>@Html.DisplayFor(_ => task.Status)</td>
            <td>@Html.DisplayFor(_ => task.Priority)</td>
            <td>@Html.DisplayFor(_ => task.Description)</td>
            <td>@((ViewBag.Projects as IEnumerable<SelectListItem>)?.FirstOrDefault(x => x.Value == task.ProjectId.ToString())?.Text)</td>   
            <td class="text-center ">
                <a asp-action="Edit" class="btn btn-primary" asp-route-id="@task.Id">Edit</a>
            </td>
            <td class="text-center ">
                <a asp-action="Delete" class="btn btn-danger" asp-route-id="@task.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>